name: Create Beta Release
on:
    workflow_dispatch:
jobs:
    upload-beta:
        uses: cumulus-actions/standard-workflows/.github/workflows/beta-2gp.yml@main
        secrets:
            dev-hub-auth-url: "${{ secrets.DEV_HUB_AUTH_URL }}"