name: Upload Beta Release
on:
    workflow_dispatch:
jobs:
    upload-beta:
        # Replace this URL with your forked repo.
        # Use the `beta-2gp` workflow if this is a 2GP project.
        uses: cumulus-actions/standard-workflows/.github/workflows/beta-2gp.yml@main
        secrets:
            # If this is a 2GP project, omit the packaging org auth URL.
            dev-hub-auth-url: "${{ secrets.DEV_HUB_AUTH_URL }}"